#**6-1 文件的預處理**



*    **向量化**，原始文件無法輸入至模型，需轉成數值張量

*   舉例過程: Text(文件) -> Tokens -> Vector encoding of the tokens



    ---  Token: 小單元，通常是文件字串裡分隔開的單詞





*   n元語法: 請參考6-4



*   **轉換成向量的方法**
1.   One Hot Encoding
2.   Token Embedding Token 嵌入法





---



---



# **6-1-1 單字和字元的One Hot Encoding**

    ---   本章節使用的案例為第3章提過的IDMB資料集



程式 6.1 單字的One-Hot Encoding(簡易版) 未處理標點符號

In [0]:
import numpy as np

samples = ['The cat sat on the mat.','The dog ate my homework.']

# 空dict，儲存tokens和tokens的key
token_index = {}

# 建立字典
for sample in samples:
  for word in sample.split():
    if word not in token_index:
      token_index[word] = len(token_index) + 1

# 將token轉成向量
max_length = 10
# 建立Numpy Array，使用numpy.zeros()先將所有設為0
results = np.zeros(shape=(len(samples), max_length, max(token_index.values())+1))
# shape = (2, 10, 11)，2個樣本；只看前10個文字，所以有10個token；索引位置至11，因為0不用看
#print(results.shape)

for i, sample in enumerate(samples):
  for j, word in list(enumerate(sample.split()))[:max_length]:
    index = token_index.get(word)
    results[i, j, index] = 1
#print(token_index)
print(results)

[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


程式 6.2 字元的One-Hot Encoding(簡易版) 未處理標點符號

In [0]:
import string

samples = ['The cat sat on the mat.','The dog ate my homework.'] 
characters = string.printable         # 所有可印出的ASCII字元的字串
#print(len(characters))                # 共有100種token

token_index = dict(zip(characters, range(1, len(characters)+1)))
#print(token_index)

max_length = 50
results = np.zeros((len(samples),max_length, max(token_index.values())+1))

#print(results.shape)                     # (2, 50, 101),2個樣本,只看樣本前50字,100種token，0不使用
for i, sample in enumerate(samples):
  for j, character in enumerate(sample):
    index = token_index.get(character)
    results[i, j , index] = 1
print(results)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


程式 6-3 使用keras作文字的encoding

In [0]:
from keras.preprocessing.text import Tokenizer

samples = ['The cat sat on the mat.','The dog ate my homework.']

tokenizer = Tokenizer(num_words=1000)           # 建立分詞器，處理前1000個單字
tokenizer.fit_on_texts(samples)                 # 建立dict,key_value由出現頻度以及順率決定,不使用0；# fit_on_text,設定成用來訓練的txt
sequences = tokenizer.texts_to_sequences(samples)# 將smaples裡字串的每個單字用dict轉換成整數鑑值，return a list；text_to_sequence,將txt轉換為序列
#print(sequences)

one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary') # texts_to_matrix,轉換為向量

#print(one_hot_results.shape)                     # (2, 1000),2個樣本,sample的文字對應到token位置
#print(one_hot_results[0][:15])
#print(one_hot_results[1][:15])

word_index = tokenizer.word_index                 # 取得單字與索引間的對應關聯      
print(len(word_index))                            # 找到9個唯一的tokens

9


程式 6-4 使用雜湊技巧One-hot hashing trick的單字(簡易版),用來處理token數量太大

In [0]:
import numpy as np

dimensionality = 1000                   # 將token儲存維1000的向量
max_length = 10


results = np.zeros((len(samples), max_length, dimensionality))
for i, sample in enumerate(samples):
  for j, word in list(enumerate(sample.split()))[:max_length]:
    index = abs(hash(word)) % dimensionality
    results[i, j, index] = 1
#print(results.shape)
print(results)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


程式 6-5 建立一個嵌入層

In [0]:
from keras.layers import Embedding
embedding_layer = Embedding(1000, 64) # 1000為可能的token數，64為要輸入的向量維數

程式 6-6 載入IMDB Data Sets，整理成適合供Embedding層使用的資料

In [0]:
from keras.datasets import imdb
from keras import preprocessing

max_features = 1000 # 設定作為特徵的最常用文字數量
max_len = 20 # 只用每篇文章最前面的20個字

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words = max_features)

#print(x_train.shape) # (25000,)為25000筆評論(樣本)
# 將list轉換為2d整數張量, shape為(sample數量, 最大長度)
x_train = preprocessing.sequence.pad_sequences(x_train, maxlen = max_len)
#print(x_train.shape)  # (25000, 20)只看前20個字
#print(x_train[0])

x_test = preprocessing.sequence.pad_sequences(x_test, maxlen = max_len)
#print(x_test)

[[286 170   8 ...  14   6 717]
 [ 10  10 472 ... 125   4   2]
 [ 34   2  45 ...   9  57 975]
 ...
 [226  20 272 ...  21 846   2]
 [ 55 117 212 ...   2   7 470]
 [ 19  14  20 ...  34   2   2]]


程式 6-7 把imdb資料提供給Embedding Layer和分類器

In [0]:
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding

model = Sequential()
model.add(Embedding(10000, 8, input_length = max_len)) # 8為輸入維度
model.add(Flatten()) # 展平為2d向量

model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['acc'])
model.summary()

history = model.fit(x_train, y_train, epochs = 10, batch_size = 32, validation_split = 0.2)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
flatten_2 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 2s 79us/step - loss: 0.6798 - acc: 0.5842 - val_loss: 0.6441 - val_acc: 0.6794
Epoch 2/10
20000/20000 [==============================] - 1s 62us/step - loss: 0.5789 - acc: 0.7236 - val_loss: 0.5539 - val_acc: 0.7068
Epoch 3/10
20000/20000 [==============================] - 1s 62us/step - loss: 0.5114 - acc: 0.7498 - val_loss: 0.5306 - val_acc: 0.7240
Epoch 4/10
20000/20000 [==============================] - 1s 61us/step - loss: 0.4872 - acc: 0.7641 - val_loss: 0.5258 - val_acc: 0.7316
Epoch 5/10
20000/20000 [==============================] - 1s 64us/step - loss: 0.4752 - acc: 0.7704 - val_loss: 0.5253 - val_acc: 0.7358
Epoch 6/10
20000/20000 [==============================] - 1s 65us/step - loss: 0.4664 - acc: 0.7759 - val_loss: 0.5284 - val_acc: 0.7326
Epoch 7/10
20000/20000 [==============================] - 1s 61us/step - loss: 0.4580 - acc: 0.7807 - val_loss: 0.5300 - val_acc:

!Error 程式 6-8, 處理原始IMDB資料的標籤

In [0]:
import os
from google.colab import files

imdb_dir = 'D:/DataSets_for_Python/aclImdb'
train_dir = os.path.join(imdb_dir, 'train')

labels = []
texts = []

for label_type in ['neg', 'pos']:
    dir_name = os.path.join(train_dir, label_type)
    for fname in os.listdir(dir_name):
        if fname[-4:] == '.txt':
            f = open(os.path.join(dir_name, fname), encoding = 'utf8')
            texts.append(f.read())
            f.close()
            if label_type == 'neg':
                labels.append(0)
            else:
                labels.append(1)
print(len(texts))


FileNotFoundError: ignored

!Error 程式 6-9 對原始IMDB資料的文字資料進行向量化

In [0]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

maxlen = 100  # 100 個文字後切斷評論 (只看評論的前 100 個字)
training_samples = 200  # 以 200 個樣本進行訓練
validation_samples = 10000 # 以 10, 000 個樣本進行驗證
max_words = 10000  # 僅考慮資料集中的前 10, 000 個單詞

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts) # 將文字轉成整數 list 的序列資料

word_index = tokenizer.word_index
print(word_index[: 10])
print('共使用了 %s 個 token 字詞.' % len(word_index))

data = pad_sequences(sequences, maxlen=maxlen) # 只取每個評論的前 100 個字 (多切少補) 作為資料張量
labels = np.asarray(labels)  # 將標籤 list 轉為 Numpy array (標籤張量)

print('資料張量 shape:', data.shape) # (25000, 100)
print('標籤張量 shape:', labels.shape) # (25000,)

indices = np.arange(data.shape[0])  # 將資料拆分為訓練集和驗證集, 但首先要將資料打散, 因為所處理的資料是有順序性的樣本資料 (負評在前, 然後才是正評)
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]

x_train = data[:training_samples]
y_train = labels[:training_samples]
x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

0


!Error 程式 6-10 解析Glove文字嵌入向量檔案

In [0]:
glove_dir = 'D:\DataSets_for_Python\glove.6B'

embedding_index = {}

f = open(os.path.join(glove_dir, 'glove.68.100d.txt'))

for line in f:
  values = line.split()
  word = values[0]
  coefs = np.asarray(values[1:], dtype='float32')
  embedding_index[word] = coefs
f.close()

print(len(embedding_index))

FileNotFoundError: ignored

!Error 程式 6-11 準備GloVe文字嵌入向量矩陣

In [0]:
embedding_dim = 100

embedding_matrix = np.zeros((max_words, embedding_dim))
print(embedding_matrix.shape)

for word, i in word_index.items():
  if i < max_words:
    embedding_vector = embedding_index.get(word)
    if embedding_vector is not Noe:
      embedding_matrix[i] = embedding_vector

(10000, 100)


!Error 程式 6-12 定義模型

In [0]:
from keras.models import Sequentail
from keras.layers import Embedding, Flatten, Dense

model = Sequential()

model.add(Embedding(max_words, embedding_dim, input_length = max_len))
model.add(Flatten())
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))
model.summary()

ImportError: ignored

程式 6-13 訓練和驗證

In [0]:
model.compile(optimizer = 'rmsprop',loss='binary_crossentropy',metrics = ['acc'])
history = model.fit(x_train, y_train, epochs = 10, batch_size = 32,validation_data = [x_val, y_val])
model.save_weights('pre_trained_glove_model.h5')

NameError: ignored

程式 6-14 繪製結果

In [0]:
import matplotlib.pyplot as plt

acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

程式 6.15 訓練相同模型而不使用預先訓練的文字嵌入向量

In [0]:
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense

model = Sequential()
model.add(Embedding(max_words, embedding_dim, input_length=maxlen))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])

history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=32,
                    validation_data=(x_val, y_val))


############### 繪製
import matplotlib.pyplot as plt

acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

程式 6.16 對測試資料進行分詞

In [0]:
test_dir = os.path.join(imdb_dir, 'test')

labels = []
texts = []

for label_type in ['neg', 'pos']:
	dir_name = os.path.join(test_dir, label_type)
	for fname in sorted(os.listdir(dir_name)):
		if fname[-4:] == '.txt':
			f = open(os.path.join(dir_name, fname), encoding='UTF-8')
			texts.append(f.read())
			f.close()
			if label_type == 'neg':
				labels.append(0)
			else:
				labels.append(1)

sequences = tokenizer.texts_to_sequences(texts)
x_test = pad_sequences(sequences, maxlen=maxlen)
y_test = np.asarray(labels)

model.load_weights('pre_trained_glove_model.h5')
model.evaluate(x_test, y_test)